### ISSUE TITLE
Can not import pydantic with latest docker image

### ISSUE THREAD

**Issue by renan-r-santos** [colesbury/nogil#21] opened 2021-10-21 21:15 UTC
I get an error when trying to import pydantic using the latest [image](https://hub.docker.com/r/colesbury/python-nogil).

[pip.log](https://github.com/colesbury/nogil/files/7392805/pip.log)

```
root@f597b6f2e89e:~# python3
Python 3.9.0a4+ (default, Oct 17 2021, 19:16:30)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 7, in init pydantic.dataclasses
    import builtins
  File "pydantic/main.py", line 376, in init pydantic.main
  File "pydantic/main.py", line 369, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 205, in pydantic.utils.generate_model_signature
  File "/usr/local/lib/python3.9/inspect.py", line 3076, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/lib/python3.9/inspect.py", line 2825, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/local/lib/python3.9/inspect.py", line 2280, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/usr/local/lib/python3.9/inspect.py", line 2091, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <cyfunction BaseModel.__init__ at 0x58f257d9bd0>
```

**Comment by colesbury** [comment] 2021-10-21 22:30
Thanks for the bug report. I can reproduce the problem and will have a fix soon.

**Comment by colesbury** [comment] 2021-10-21 23:49
The ImportError is fixed now. You'll need to run `docker pull colesbury/python-nogil` to get the latest image.

Please let me know if you run into any more issues. (It's also helpful to know if you *don't* run into issues.)

Three of the pydantic test cases still fail (out of ~2000); the failures are not GIL related, but rather because this nogil Python is based off of Python 3.9.0a3, which is missing some typing related features from the 3.9 final release. I'm not sure the broken tests reflect issues that will come up in practice. Either way, they should be fixed once I finish rebasing the nogil changes on top of the v3.9.7 release, but that's still a few weeks from completion.

**Comment by renan-r-santos** [comment] 2021-10-22 00:42
Just tested here and no issues :)
Thank you very much for the prompt fix and detailed explanation.

**Closed as completed** 2021-10-22 03:10 UTC

**Comment by fengyang95** [comment] 2021-12-23 03:14
> 



> The ImportError is fixed now. You'll need to run `docker pull colesbury/python-nogil` to get the latest image.
> 
> Please let me know if you run into any more issues. (It's also helpful to know if you _don't_ run into issues.)
> 
> Three of the pydantic test cases still fail (out of ~2000); the failures are not GIL related, but rather because this nogil Python is based off of Python 3.9.0a3, which is missing some typing related features from the 3.9 final release. I'm not sure the broken tests reflect issues that will come up in practice. Either way, they should be fixed once I finish rebasing the nogil changes on top of the v3.9.7 release, but that's still a few weeks from completion.

I want to know if you have completed this update? I encountered some problems when using pydantic. Here comes the error:
 
Modules/gcmodule.c:2674: PyObject_GC_Track: Assertion failed: object already tracked by the garbage collector
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x52d684301d0
object refcount : 1
object type     : 0x7f8f55d01fc0
object type name: pydantic.main.__pyx_scope_struct_5__get_value
object repr     :

**Comment by colesbury** [comment] 2021-12-23 15:19
> I want to know if you have completed this update? I encountered some problems when using pydantic. Here comes the error

No, it's nearly done, but I have not rebuilt the docker images or extensions yet. Can you provide more details about how to reproduce the issue? I'd like to make sure the bug is fixed before releasing a new build.

**Comment by fengyang95** [comment] 2021-12-24 03:24
> 

Sorry, I found that my code was not correct, not caused by pydantic module.

**Comment by fengyang95** [comment] 2021-12-26 04:45
> > I want to know if you have completed this update? I encountered some problems when using pydantic. Here comes the error
> 
> No, it's nearly done, but I have not rebuilt the docker images or extensions yet. Can you provide more details about how to reproduce the issue? I'd like to make sure the bug is fixed before releasing a new build.

Run the following script with nogil:latest, there is a probability of gc error，hope to get your help

Modules/gcmodule.c:2674: 

```
# -*- coding: utf-8 -*-
from concurrent import futures
import logging
from typing import Dict, Any
from pydantic import BaseModel


class EntitySmall(BaseModel):
    name: str
    value: int


def func(data_dict: Dict[str, Any]) -> Dict[str, Any]:
    entity = EntitySmall(**data_dict)
    new_data_dict = entity.dict()
    return new_data_dict


test_datas = [
    {"name": f"name{i}", "value": i} for i in range(1000)
]

if __name__ == "__main__":
    to_do_map = {}
    with futures.ThreadPoolExecutor(max_workers=20) as THREAD_POOL:
        for i, data in enumerate(test_datas):
            future = THREAD_POOL.submit(func, data)
            to_do_map[future] = i
        done_iter = futures.as_completed(to_do_map, timeout=100)
        for future in done_iter:
            logging.error(f"future:{to_do_map[future]}")
            logging.error(future.result())
```

**Comment by colesbury** [comment] 2021-12-28 16:41
@fengyang95 Thanks, I'm able to reproduce the issue. I've opened a new issue #28 to track the bug. I should have a fix soon.
